In [2]:
import numpy as np

In [5]:
X = np.array([[0.5,0.1], [0.2,0.6]])
print(X.shape)
Y = np.array([[0.7],[0.8]])
print(Y.shape)




(2, 2)
(2, 1)


In [7]:
theta1 = np.array([[0.5,0.2],[0.6,-0.1],[-0.4,-0.3]])

print(theta1.shape)

theta2 = np.array([[0.7,-0.1,0.2]])
print(theta2.shape)

(3, 2)
(1, 3)


Forward Pass

In [9]:
z1 = np.matmul(X, theta1.T)
print(z1.shape)
print(z1)

(2, 3)
[[ 0.27  0.29 -0.23]
 [ 0.22  0.06 -0.26]]


In [11]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [ ]:
a1 = sigmoid(z1)

(2, 3)


In [17]:
z2 = np.matmul(a1,theta2.T)
print(z2.shape)
print(z2)


(2, 1)
[[0.42831585]
 [0.42391866]]


In [18]:
a2 = sigmoid(z2)
print(a2.shape)
print(a2)

(2, 1)
[[0.60547144]
 [0.60442057]]


In [22]:
# lOSS FUnction

loss = 0.5 * np.matmul((Y - a2).T,(Y - a2))
print(loss)

[[0.02359348]]


In [23]:
#Backward

delta2 = (a2 - Y) * a2 * (1-a2)
delta2

array([[-0.02258058],
       [-0.04676233]])

In [24]:
delta1 = np.matmul(delta2,theta2) * a1 * (1-a1)
delta1

array([[-0.00388045,  0.00055281, -0.00111423],
       [-0.00808518,  0.00116801, -0.00229904]])

In [ ]:
djdtheta2 = np.matmul(delta2.T,a1)
print(djdtheta2.shape)

(1, 3)
[[-0.03874806 -0.03699839 -0.03035622]]


In [26]:
djdtheta1 = np.matmul(delta1.T,X)
print(djdtheta1.shape)

(3, 2)


In [28]:
theta2 = theta2 - 0.1 * djdtheta2
theta1 = theta1 - 0.1 * djdtheta1
print(theta2)
print(theta1)

[[ 0.70387481 -0.09630016  0.20303562]]
[[ 0.50035573  0.20052392]
 [ 0.599949   -0.10007561]
 [-0.39989831 -0.29985092]]
